number1=float(input("Įveskite bet kokį skaičių: "))
number2=float(input("Įveskite kitą bet kokį skaičių: "))
print(f"Daugyba yra {number1 * number2}")
print(f"Dalmuo yra {number1 / number2}")
print(f"Suma yra {number1 + number2}")
print(f"Atimtis yra {number1 - number2}")
print(f"// yra {number1 // number2}")
print(f"Liekna yra {number1 % number2}")
print(f"Kėlimas laipsniu yra {number1 ** number2}")